sudo: required

services:
  - docker
before_install:
  - docker build -t vladiyeki/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run vladiyeki/react-test -- --coverage

after_success:
  - docker build -t vladiyeki/multi-client ./client
  - docker build -t vladiyeki/multi-nginx ./nginx
  - docker build -t vladiyeki/multi-server ./server
  - docker build -t vladiyeki/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push vladiyeki/multi-client
  - docker push vladiyeki/multi-nginx
  - docker push vladiyeki/multi-server
  - docker push vladiyeki/multi-worker 
  #test